// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReOrderlyWeb.Data.Sql;

#nullable disable

namespace ReOrderlyWeb.SQL.Data.Migrations
{
    [DbContext(typeof(ReOrderlyWebDbContext))]
    [Migration("20240923201138_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"));

                    b.Property<int?>("OrderItemsorderItemId")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<DateOnly>("orderDate")
                        .HasColumnType("date");

                    b.Property<int>("orderStatus")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("OrderItemsorderItemId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.OrderItems", b =>
                {
                    b.Property<int>("orderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderItemId"));

                    b.Property<int>("idOrder")
                        .HasColumnType("int");

                    b.Property<int>("idProduct")
                        .HasColumnType("int");

                    b.Property<int>("orderItemQuantity")
                        .HasColumnType("int");

                    b.Property<int>("orderPrice")
                        .HasColumnType("int");

                    b.HasKey("orderItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.OrderStatus", b =>
                {
                    b.Property<int>("orderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderStatusId"));

                    b.Property<int?>("orderId")
                        .HasColumnType("int");

                    b.Property<string>("orderStatusDescription")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("orderStatusId");

                    b.HasIndex("orderId");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.OrderSubscription", b =>
                {
                    b.Property<int>("orderSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderSubscriptionId"));

                    b.Property<int>("idProduct")
                        .HasColumnType("int");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.Property<int>("intervalDays")
                        .HasColumnType("int");

                    b.Property<DateOnly>("orderDate")
                        .HasColumnType("date");

                    b.HasKey("orderSubscriptionId");

                    b.ToTable("OrderSubscription");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.Products", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<int?>("OrderItemsorderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("orderSubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("productPrice")
                        .HasColumnType("float");

                    b.Property<int>("productQuantity")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("OrderItemsorderItemId");

                    b.HasIndex("orderSubscriptionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("country")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("houseNumber")
                        .HasColumnType("int");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("orderId")
                        .HasColumnType("int");

                    b.Property<int?>("orderSubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("phoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("streetName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("voivodeship")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("zipcode")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.HasIndex("orderId");

                    b.HasIndex("orderSubscriptionId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.Order", b =>
                {
                    b.HasOne("ReOrderlyWeb.SQL.Data.DAO.OrderItems", null)
                        .WithMany("Orders")
                        .HasForeignKey("OrderItemsorderItemId");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.OrderStatus", b =>
                {
                    b.HasOne("ReOrderlyWeb.SQL.Data.DAO.Order", null)
                        .WithMany("OrderStatuss")
                        .HasForeignKey("orderId");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.Products", b =>
                {
                    b.HasOne("ReOrderlyWeb.SQL.Data.DAO.OrderItems", null)
                        .WithMany("Productss")
                        .HasForeignKey("OrderItemsorderItemId");

                    b.HasOne("ReOrderlyWeb.SQL.Data.DAO.OrderSubscription", null)
                        .WithMany("Productss")
                        .HasForeignKey("orderSubscriptionId");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.User", b =>
                {
                    b.HasOne("ReOrderlyWeb.SQL.Data.DAO.Order", null)
                        .WithMany("Users")
                        .HasForeignKey("orderId");

                    b.HasOne("ReOrderlyWeb.SQL.Data.DAO.OrderSubscription", null)
                        .WithMany("Users")
                        .HasForeignKey("orderSubscriptionId");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.Order", b =>
                {
                    b.Navigation("OrderStatuss");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.OrderItems", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Productss");
                });

            modelBuilder.Entity("ReOrderlyWeb.SQL.Data.DAO.OrderSubscription", b =>
                {
                    b.Navigation("Productss");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
